movies/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    add_data,
    all_movies,
    director_list,
    genre_list,
    movie_details,
    genre_movie,
    movie_search,
    create_movie,
    recommend,
    get_popular,
    get_genre_popular
)
app_name = 'movies'

urlpatterns = [
    path('api/movie',all_movies),
    path('api/movie/<int:movie_id>',movie_details),
    path('api/movie/genre/<int:genre_id>',genre_movie),
    path('api/movie/search',movie_search),
    path('api/movie/create',create_movie),
    path('api/director',director_list),
    path('api/genre',genre_list),
    path('api/recommend',recommend),
    path('api/popular',get_popular),
    path('api/popular/genre/movie',get_genre_popular),
    path('add/',add_data)
]

recommenderSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/',include('movies.urls',namespace='movies')),
    path('user/',include('accounts.urls',namespace='accounts')),
    path('',include('frontend.urls',namespace='frontend')),
] + staticfiles_urlpatterns()

templates/pages/auth.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<link rel="stylesheet" href="{% static 'css/login_signup.css' %}">

{% endblock script %}
{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto p-0">
            <div class="card">
                <div class="login-box">
                    <div class="login-snip"> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label> <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                        <div class="login-space">
                            <div class="login">
                                <!-- {{ form.as_p }} -->
                                <form class="form" method="post" action="/user/login">
                                    {% csrf_token %}
                                    <input type="hidden" name="login" value="1">
                                <div class="group">
                                    <label for="user" class="label">Username</label> 
                                    <input id="user" type="text" name="username" required maxlength="150" autocomplete="username" autofocus autocapitalize="none" class="input" placeholder="Enter your username"> 
                                </div>
                                <div class="group">
                                    <label for="pass" class="label">Password</label> 
                                    <input id="pass" type="password" required autocomplete="current-password" name="password" class="input" data-type="password" placeholder="Enter your password"> 
                                </div>
                                <div class="group">
                                    <input id="check" type="checkbox" class="check" checked> 
                                    <label for="check"><span class="icon"></span> Keep me Signed in</label> 
                                </div>
                                    <div class="group"> <input type="submit" class="button" value="Sign In"> </div>
                                </form>
                                <div class="hr"></div>
                                <div class="foot"> <a  class="label" href="#">Forgot Password?</a> </div>
                            </div>
                            <div class="sign-up-form">
                                <form class="form" method="post" action="/user/login">
                                {% csrf_token %}
                                <div class="group"> <label for="user" class="label">Username</label> <input id="user" type="text" name="username" required maxlength="150" autocomplete="username" autofocus autocapitalize="none" class="input" placeholder="Create your Username"> </div>
                                <div class="group"> <label for="pass" class="label">Password</label> <input id="pass" type="password" required autocomplete="current-password" name="password1" class="input" data-type="password" placeholder="Create your password"> </div>
                                <div class="group"> <label for="pass" class="label">Repeat Password</label> <input id="pass" type="password" required autocomplete="current-password" name="password2" class="input" data-type="password" placeholder="Repeat your password"> </div>
                                <div class="group"> <label for="pass" class="label">Email Address</label> <input id="pass" type="email" required autocomplete="current-password" name="email" class="input" placeholder="Enter your email address"> </div>
                                <div class="group"> <input type="submit" class="button" value="Sign Up"> </div>
                                <div class="hr"></div>
                                <div class="foot"> <label class="label" for="tab-1">Already Member?</label> </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let logout = document.getElementById("logout")
    let form = document.getElementById("form")
    let home = document.getElementById("home")
    let prof = document.getElementById("prof")
    prof.classList.add("d-none")
    logout.classList.add("d-none")
    form.classList.add("d-none")
    home.classList.add("d-none")

    // lookup('movie/api/movie',null,'GET',(response,status)=>{
    //     console.log(`callback Response ${response,status}`)
    // })
</script>
{% endblock %}

templates/pages/dashboard.html
{% extends 'base.html' %}
{% load static %}


  {% block script %}
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/421ca813ee.js" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
  {% endblock script %}

  {% block content %}
  <div class="container">
    <br>
    <h1 style="color: #8b1b33;">Recommended movies for you</h1>
    <br>
    <div class="row row-cols-1 row-cols-md-3 g-4" id="RecommendMovies">
    </div>
  </div>

  <div class="container">
    <br>
    <h1 style="color: #8b1b33;">Popular on Netflix</h1>
    <br>
    <div class="row row-cols-1 row-cols-md-3 g-4" id="popMovies">

    </div>
  </div>

  <div class="container">
    <br>
    <h1 style="color: #8b1b33;">Genres</h1>
    <h3 id="genre" style="color: #8b1b33;">Action</h3>
    <br>
    <div class="row row-cols-1 row-cols-md-3 g-4" id="GenreMovies">
    </div>
  </div>



  <script>
    const card = (res) => `<div class="col col-lg-3">
        <div class="card c-height">
          <div class="image">
          <img src="https://www.popcorn.app/assets/app/images/placeholder-movieimage.png"
            class="card-img-top" alt="...">
          </div>
          <div class="card-body">
            <h5 class="card-title">${res.name}</h5>
            <p class="card-text">${res.description}</p>
            <a href="/movie/${res.id}" class="btn btn-primary">Check details</a>
          </div>
        </div>
      </div>`

      const loadMovies = (loc,response) =>{
        for (let c of response){
          loc.innerHTML += card(c)
        }
      }

      lookup('movie/api/recommend',null,'GET',(response,status)=>{
        loadMovies(document.getElementById("RecommendMovies"),response)
      })
      lookup('movie/api/popular',null,'GET',(response,status)=>{
        loadMovies(document.getElementById("popMovies"),response)
      })
      lookup('movie/api/popular/genre/movie',null,'GET',(response,status)=>{
        if(response[0]){
          document.getElementById("genre").innerHTML = response[0].genre[0].genre
        }else{
          document.getElementById("genre").innerHTML = 'none'

        }
        loadMovies(document.getElementById("GenreMovies"),response)
      })
  </script>
  {% endblock content %}

templates/pages/details.html
{% include 'base.html' %}
{% load static %}
{% block script %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

<script src="https://kit.fontawesome.com/421ca813ee.js" crossorigin="anonymous"></script>
{% endblock script %}
  {% block content %}
  <div class="card mb-3 mb-31" style="max-width: 1200px;">
    <div class="row g-0">
      <div class="col-md-4 mov-img">
        <img
          src="https://www.popcorn.app/assets/app/images/placeholder-movieimage.png"
          alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p id='movie-genre'></p>
          <h1 class="card-title" id="movie-name">Movie Name: </h1>
          <p id="movie-rating"><i class="fa-size fab fa-imdb"></i><span id="rat"></span></p>
          <p class="card-text" id="movie-description"><strong>Description: </strong></p>
          <p id="movie-cast"><strong>Cast: </strong></p>
          <p><strong>Movie release date: </strong></p>
          <a href="">Watch trailer&nbsp;&nbsp;<i class="fas fa-location-arrow"></i></a>
          <a href="">Watch movie&nbsp;&nbsp;<i class="fas fa-location-arrow"></i></a>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="container">
    <form method="POST" id="form_">
      <h1>Comment Section</h1>
      <br>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label"><strong>Review</strong></label>
        <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Start typing here..." rows="3"></textarea>
      </div>
      <div class="rate">
        <h5><strong>Rate this movie</strong></h5>
        <input type="radio" id="star5" name="rate" value="5" />
        <label for="star5" title="text">5 stars</label>
        <input type="radio" id="star4" name="rate" value="4" />
        <label for="star4" title="text">4 stars</label>
        <input type="radio" id="star3" name="rate" value="3" />
        <label for="star3" title="text">3 stars</label>
        <input type="radio" id="star2" name="rate" value="2" />
        <label for="star2" title="text">2 stars</label>
        <input type="radio" id="star1" name="rate" value="1" />
        <label for="star1" title="text">1 star</label>
      </div><br><br><br><br>

      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  </div>
  <script>
    const data = document.URL.split('/')
    const id = data[data.length-1]
    lookup(`http://127.0.0.1:8000/movie/api/movie/${id}`,null,'GET',(response,status)=>{
      document.getElementById("movie-name").innerHTML = response.name
      document.getElementById("movie-description").innerHTML += response.description
      document.getElementById("rat").innerHTML = response.rating
      document.getElementById("movie-cast").innerHTML += response.cast
      for (let c of response.genre){
        if (response.genre.indexOf(c) == response.genre.length-1){
          document.getElementById("movie-genre").innerHTML += c.genre
        }else{
          document.getElementById("movie-genre").innerHTML += c.genre + ', '
        }
      }
    })
    document.getElementById("form_").addEventListener("submit",(event)=>{
      event.preventDefault()
      console.log(document.querySelectorAll('input[name="rate"]'))
      let rat = null
      for (let c of document.querySelectorAll('input[name="rate"]')){
        if (c.checked){
          rat = c.value
        }
      }
      lookup('http://127.0.0.1:8000/user/watch',{
        movies:id,
        user_rating:rat,
        comments:document.getElementById("exampleFormControlTextarea1").value
      },'POST',(response)=>{
        console.log(response)
        document.getElementById("exampleFormControlTextarea1").value = null
        for (let c of document.querySelectorAll('input[name="rate"]')){
          c.checked = false
        }
      })
    })
  </script>

{% endblock content %}

templates/pages/home.html
{% load static %}
<body>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script src="https://kit.fontawesome.com/421ca813ee.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
    </head>

    <body>
        <section class="header">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" id="navbar-brand" href="#">MovieBox</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto text-right">
                            <li class="nav-item">
                                <a class="nav-link" id="contact-us" href="#">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <div class="row banner">
                    <div class="col-md-6">
                        <h1>BINGE IT OUT!</h1>
                        <!-- <h1><br>For the <span id="hero">Spider-Man</span></h1> -->
                        <p>Enjoy your popcorn and enjoy the show. It's just a movie, so have fun!</p>
                        <a href="{% url 'frontend:login' %}" class="express-btn">Sign-up/Sign-in&nbsp;<i class="fas fa-location-arrow"></i></a>
                    </div>
                    <div class="col-md-6">
                        <img src="http://www.pngall.com/wp-content/uploads/2016/05/Spider-Man-PNG-Picture.png"
                            class="img-fluid">
                    </div>
                </div>
            </div>
        </section>
    </body>
    </html>
</body>
</html>

templates/pages/profile.html
{% extends 'base.html' %}
{% load static %}


{% block script %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock script %}

{% block content %}
<div class="container-fluid">
    <div class="row py-5 px-4">
        <div class="col-md-5 mx-auto">
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-0 pb-4 cover">
                    <div class="media align-items-end profile-head">
                        <div class="profile mr-3"><img
                                src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80"
                                alt="..." width="130" class="rounded mb-2 img-thumbnail" id="img">
                            <div class="media-body mb-5 text-white">
                                <h4 class="mt-0 mb-0">{{user}}</h4>
                                <p class="small mb-4"><i class="far fa-envelope mr-2"></i>&nbsp;{{ user.email }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="bg-light p-4 d-flex justify-content-end text-center row" id="details">
                        <ul class="list-inline mb-0 col-md-12">
                            <li class="list-inline-item">
                                <h5 class="font-weight-bold mb-0 d-block">Movies watched</h5>
                                <small class="text-muted" id="count">{{ data.count }}
                            </li>
                        </ul>
                    </div>
                    <div class="py-4 px-4 r-movies">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <h5 class="mb-0 r-movies">Recent movies watched</h5>
                        </div>
                        <div class="row" id="movies">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let str = (c) => `<div class="col-lg-6 mb-2 pr-lg-1 movie-box"><img
                                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA7ivEX6cqgLU7UJDkmu_SH8N99XLfG4MuxA&usqp=CAU"
                                    alt="" class="img-fluid rounded shadow-sm"><br><div class="movie-name">${c.movies}</div></div>`

        const loadMovies = (loc,response) =>{
            for (let c of response){
              loc.innerHTML += str(c)
            }
        }
        lookup('user/watched',null,'GET',(response,status)=>{
            loadMovies(document.getElementById("movies"),response.slice(0,3))
        })
    </script>
{% endblock content %}