accounts/urls.py
from django.urls import path
from .views import (
    login_view,
    logout_view,
    watched_movie,
    history
)
app_name = 'accounts'

urlpatterns = [
    path('login',login_view),
    path('logout',logout_view,name='log'),
    path('watch',watched_movie),
    path('watched',history),
]

frontend/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    dashboard_page,
    profile_page,
    login_reg_page,
    movie_details_page
)
app_name = 'frontend'

urlpatterns = [
    path('movie/<int:movie_id>',movie_details_page,name='detail'),
    path('login',login_reg_page,name='login'),
    path('profile',profile_page,name='profile'),
    path('dashboard',dashboard_page,name='dashboard'),
    path('',TemplateView.as_view(template_name="pages/home.html")),
]

movies/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import (
    add_data,
    all_movies,
    director_list,
    genre_list,
    movie_details,
    genre_movie,
    movie_search,
    create_movie,
    recommend,
    get_popular,
    get_genre_popular
)
app_name = 'movies'

urlpatterns = [
    path('api/movie',all_movies),
    path('api/movie/<int:movie_id>',movie_details),
    path('api/movie/genre/<int:genre_id>',genre_movie),
    path('api/movie/search',movie_search),
    path('api/movie/create',create_movie),
    path('api/director',director_list),
    path('api/genre',genre_list),
    path('api/recommend',recommend),
    path('api/popular',get_popular),
    path('api/popular/genre/movie',get_genre_popular),
    path('add/',add_data)
]

recommenderSystem/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/',include('movies.urls',namespace='movies')),
    path('user/',include('accounts.urls',namespace='accounts')),
    path('',include('frontend.urls',namespace='frontend')),
] + staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/421ca813ee.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<script src="{% static 'js/lookup.js' %}"></script>
<link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Orelega+One&display=swap" rel="stylesheet">
{% block script %}

{% endblock script %}
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" id="navbar-brand" href="#">MovieBox</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" id="home" href="{% url 'frontend:dashboard' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" id="prof" style="margin-left: 40px;" href="{% url 'frontend:profile' %}">Profile</a>
                    </li>
                </ul>
                <form class="d-flex" id="form">

                    <label for="movie-search"></label>
                    <input list="movies_qq" autocomplete="off" id="movie_search" class="form-control search movie_search" type="search" placeholder="Search" aria-label="Search" list="movies" name="movie-search">
                    <datalist id="movies_qq">
                    </datalist>

                    <!-- <input class="form-control search" type="search" placeholder="Search" aria-label="Search"> -->
                    <button class="btn btn-primary search" type="submit" style="background-color: #e76f51; border-color: #e76f51;"><i class="fas fa-search"></i></button>
                </form>

                <!-- <button class="btn" id="logout" href="{% url 'accounts:log' %}">Logout</button> -->
                <a href="{% url 'accounts:log' %}"><button type="button" class="btn" id="logout" style="background-color: #9d0208;">Logout</button></a>
            </div>
        </div>
    </nav>
{% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script>
    document.getElementById('movie_search').addEventListener('keyup',(e)=>{
        lookup(`http://127.0.0.1:8000/movie/api/movie/search?str=${e.target.value}`,null,'GET',(response,status)=>{
            const list = document.getElementById("movies_qq")
            list.innerHTML = ""
            let count = 0
            if (status===200){
                for (let data in response){
                    list.innerHTML += `<option data-value="${response[data].id}" value="${response[data].name}"></option>`
                    count++
                    if (count>4){
                        break
                    }
                }
            }
        })

    })
    document.getElementById("form").addEventListener("submit", event =>{
        event.preventDefault()
        var form = new FormData(event.target)
        // console.log(form.get('movie-search'))
        // var value = document.querySelector("#movie_search option[value='" + form.get('movie-search') + "']");
        var value = document.querySelector("#movies_qq option[value='" + form.get('movie-search') + "']").dataset.value;
        console.log(value)
        window.location.href = `http://127.0.0.1:8000/movie/${value}`;
    })
</script>
</body>
</html>